menu:
  - general:
    - parameters:
      - prefecture
      - entities
      - customizations

      - addresses:
        - districts
        - neighborhoods
        - streets
        - street_types
        - land_subdivisions
        - condominia

      - signatures:
        - signature_configurations
        - signatures

    - users:
      - positions
      - employees
      - profiles
      - users

  - commom:
    - cadastral:
      - contracts
      - banks:
        - agencies
        - banks
        - bank_accounts
      - materials:
        - materials_classes
        - materials
        - reference_units
      - indexers
      - currencies
      - holidays

    - people:
      - people
      - creditors
      - auxiliary:
        - regularization_or_administrative_sanction_reasons
        - company_sizes
        - risk_degrees
    - legislation:
      - dissemination_sources
      - communication_sources
      - legal_text_natures
      - regulatory_act:
        - regulatory_act_types
        - regulatory_act_type_classifications
        - regulatory_acts
    - document_types
    - delivery_locations
    - payment_methods
    - contract_types
    - administration_types

  - purchasing_processes:
    - auxiliary:
      - licitation_commissions
      - trading_configuration
      - judgment_forms
      - licitation_objects
      - legal_references
    - price_collections
    - direct_purchases
    - price_registrations
    - purchase_solicitations
    - licitation_processes
    - licitation_notices
    - licitation_process_impugnments
    - licitation_process_appeals
    - tradings
