menu:
  - settings:
    - parameters:
      - prefecture
      - addresses:
        - districts
        - neighborhoods
        - streets
        - street_types
        - land_subdivisions
        - condominia

      - signatures:
        - signature_configurations
        - signatures
    - department_secretary:
      - departments
      - secretaries

    - users:
      - positions
      - employees
      - profiles
      - users
    - expense_setting:
      - expenses
      - project_activities
      - purchasing_units
      - organs
      - resource_sources
      - expense_functions
      - expense_sub_functions
      - programs
      - nature_expenses
      - purchase_forms
    - materials:
      - material_classes
      - reference_units
    - legislation:
      - dissemination_sources
      - communication_sources
      - regulatory_acts
    - document_types
    - indexers
    - currencies
    - holidays
    - regularization_or_administrative_sanction_reasons

  - register:
    - physical_peoples
    - legal_peoples
    - company_sizes
    - materials
    - delivery_locations
    - payment_methods
    - contract_types

  - purchase:
    - "Gestão do Objeto":
        - management_objects
    - purchase_solicitations
    - demands
    - price_collections

  - licitations:
    - licitation_processes
    - licitation_notices
    - licitation_commissions
    - judgment_forms
    - licitation_process_impugnments
    - licitation_process_appeals
    - process_responsibles

  - "Contratos":
    - contracts
    - additive_solicitations
    - supply_requests
    - generator_generator_supply_orders
    - supply_orders
    - supply_request_managements
    - pledge_requests
    - balance_adjustments
    - reserve_fund_requests

  - "Prestação de Contas":
    - tce_export_monthly_monitorings

  - manager:
    - secretary_settings
    - dashboard_secretaries

  - "Relatórios":
    - "Consumo":
      - report_supply_request_per_secretaries
      - report_supplier_balance_per_service_orders
      - report_balance_per_creditors
      - report_balance_per_process_and_contracts
      - report_total_products_purchases
      - report_extract_consumption_per_processes
    - "Financeiro":
      - report_contract_per_resource_sources
#      - report_total_purchase_per_element_and_natures
    - report_bidding_schedules
    - report_purchase_process_ratifications_by_periods
    - report_purchase_solicitations
    - report_purchased_item_prices
    - report_materials
    - report_contracts
    - report_licitation_processes
    - report_department_requests
    - report_pledge_requests
    - report_expenses

