menu:
  - register:
      - physical_peoples
      - legal_peoples
      - auction_employees
      - auction_creditors
      - "Gest√£o de Objeto":
            - auction_management_objects
      - auction_positions
  - auction_auctions