permissions:
  delegations:
    bidders: licitation_processes
    contract_terminations: contracts
    judgment_commission_advices: licitation_processes
    licitation_process_publications: licitation_processes
    legal_analysis_appraisals: licitation_processes
    occurrence_contractual_historics: contracts
    price_collection_proposals: price_collections
    purchase_process_accreditations: licitation_processes
    purchase_process_trading_items: licitation_processes
    purchase_process_tradings: licitation_processes
    purchase_process_trading_item_bids: licitation_processes
    purchase_solicitation_liberations: purchase_solicitations
    supply_request_attendances: supply_requests
    registration_cadastral_certificates: creditors
    purchase_process_creditor_disqualifications: licitation_processes
