profile:
  - "CADASTRO":
    - agencies
    - signatures
    - regulatory_acts
    - positions
    - material_classes
    - neighborhoods
    - branch_classifications
    - licitation_commissions
    - condominia
    - expense_setting
    - secretary_settings
    - signature_configurations
    - budget_structure_configurations
    - bank_accounts
    - creditors
    - departments
    - expenses
    - districts
    - budget_allocations
    - addresses
    - holidays
    - purchase_forms
    - resource_sources
    - judgment_forms
    - payment_methods
    - expense_functions
    - employees
    - indexers
    - delivery_locations
    - streets
    - land_subdivisions
    - demand_batches
    - materials
    - batch_materials
    - dissemination_sources
    - currencies
    - regularization_or_administrative_sanction_reasons
    - nature_expenses
    - prefecture
    - organs
    - profiles
    - people
    - company_sizes
    - programs
    - project_activities
    - registration_cadastral_certificates
    - secretaries
    - budget_structures
    - expense_sub_functions
    - street_types
    - communication_sources
    - contract_types
    - document_types
    - purchasing_units
    - reference_units
    - physical_peoples
    - legal_peoples
    - users
    - management_objects
  - "COMPRA":
    - price_collection_annuls
    - price_collection_proposal_annuls
    - purchase_solicitation_annuls
    - price_collections
    - demands
    - demand_management
    - purchase_solicitation_liberations
    - price_collection_proposals
    - purchase_solicitations
  - "CONTRATO":
    - balance_adjustments
    - contract_termination_annuls
    - contracts
    - generator_generator_supply_orders
    - supply_request_managements
    - supply_request_attendances
    - supply_orders
    - supply_requests
    - pledge_requests
    - budget_revenues
    - tce_export_monthly_monitorings
    - additive_solicitations
  - "LICITAÇÃO":
    - report_bidding_schedules
    - licitation_notices
    - direct_purchases
    - licitation_process_impugnments
    - licitation_process_appeals
    - legal_analysis_appraisals
    - licitation_processes
    - realignment_prices
    - process_responsibles
  - "RELATÓRIO":
    - report_bidding_schedules
    - report_contract_per_resource_sources
    - report_purchase_process_ratifications_by_periods
    - report_purchase_solicitations
    - report_purchased_item_prices
    - report_materials
    - report_licitation_processes
    - report_balance_per_creditors
    - report_balance_per_process_and_contracts
    - report_extract_consumption_per_processes
    - report_total_products_purchases
    - report_total_purchase_per_element_and_natures
    - report_contracts
    - report_department_requests
    - report_pledge_requests
    - report_supplier_balance_per_service_orders
    - report_supply_request_per_secretaries
    - report_supply_requests
    - report_supply_orders
    - report_expenses
    - report_creditor_materials
    - report_purchase_solicitation_items
  - "PREGÃO ELETRÔNICO":
    - physical_peoples
    - legal_peoples
    - auction_creditors
    - auction_employees
    - auction_positions
    - auction_auctions
    - auction_management_objects
    - auction_dispute_items
    - auction_appeals
    - auction_suspensions
    - auction_messages
    - auction_conversations
    - licitation_processes
    - auction_proposals


